### ISSUE TITLE
stream todo list

### ISSUE THREAD

**Issue by adamwulf** [adamwulf/simplenn#1]
- [ ] create a NeuralNet class that handles sorting the forward/back propagation calls
- [ ] create a class to manage a DAG for all the neurons.
- [ ] create an LSTM from these neurons
